services:
  ns1:
    build:
      dockerfile: bind/build/Dockerfile
      context: 
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "./bind:/bind:rw"
    command:
      - /bin/sh
      - -c
      - |
        /bind/build_files.py
        cp -r /bind/etc_bind/* /etc/bind/
        named -4 -d 4 -g
    restart: always
